##
## CS4348 - Project 1
## Justin Head (jxh122430@utdallas.edu)
##

## C compiler configuration
CC = gcc
CFLAGS = -Wall

## General configuration
EXEC = project1
OBJ = $(EXEC).o

## Default target
all: clean $(EXEC)

$(EXEC): $(OBJ)

## Clean target
clean:
	rm -f *.o $(EXEC)
